### ISSUE TITLE
Should the CodeCombat from Docker Hub work already?

### ISSUE THREAD

**Issue by alexanderadam** [frankyrumple/ope#1]
Hey Raymond,

first of all: thank you for your work.

I'm not quite sure whether this is the right place to ask or whether you are the right person to ask (on the account `kgonyo` is a fork of this?).

However, I would love to run [CodeCombat](https://github.com/codecombat/codecombat) in a Docker container for offline usage and saw that there is [a pretty new entry on Docker Hub (`operepo/ope-codecombat`)](https://hub.docker.com/r/operepo/ope-codecombat/).

Although it's not linked on Docker Hub I guess you or [kgnoyo](https://github.com/kgonyo) are the the creator of this entry, right?

However, I tried to run it but somehow it doesn't work. I installed `netstat` from `net-tools` within the container to check for listening applications and I saw just the `mongod` listening so far. No application on port `3000` (or any other):

```shell
root@codecombat:/# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      0          1342080     19/mongod
```

Therefore I just wanted to ask whether the [Dockerfile](https://github.com/frankyrumple/ope/blob/master/docker_build_files/ope-codecombat/Dockerfile) is supposed to work already and whether the [repo `operepo/ope-codecombat` on Docker Hub](https://hub.docker.com/r/operepo/ope-codecombat/) is up to date.

Thank you in advance and have a nice day!

**Comment by frankyrumple** [comment]
Yes, your at the right place. Kgonyo is helping me work on this project.

It was working, but I noticed last time that it was making the CPU crank longer than it should. I am guessing  versions changed or something (e.g. newer node got pulled in?).

On the initial startup, it dumps current users, then imports the current database (can take a several minutes), so you won't see the web connection pop up until that is done. You should see the CPU cranking for a bit while it does this (docker status??)

You need to make sure you set the ports/volumes properly (see the docker-compose-include file) so that it can save user data and not rebuild the database every time it starts.

It is setup to run as a larger set of apps for the OPE project for prison education that includes canvas, khan, jsbin, etc...

To move things offline, we start/build online, then use docker save to dump a binary image, copy it inside and do docker load to import it.

I will check on it this weekend and verify if it is working for me still or if it needs some tweaks.

**Comment by frankyrumple** [comment]
I am pushing an updated copy now. rebuilt with newer node and ruby.  It comes up for me after the initial startup wait for the db to import.

**Comment by alexanderadam** [comment]
Awesome, thank you for your work!
I won't be able to test it before tuesday but I will write when I know whether it works.

**Comment by alexanderadam** [comment]
Sorry for the late response.
Current docker images work perfectly. 👍 

Thank you, awesome work.

Have a nice week!
